CREATE TABLE public.student (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "name" text,
    username text,
    email text UNIQUE ,
    password text,
    app_user_role text,
    locked BOOLEAN,
    enable BOOLEAN,
    created timestamp,
    created_by text,
    updated timestamp,
    updated_by text,
    CONSTRAINT student_pkey PRIMARY KEY (id)
);
ALTER TABLE public.student
    OWNER to postgres;

